// src/constants/categories.js
import { imageDB } from "./imageData";

export const LS_KEY = "categoryPrefs.v1";

// ✅ 기본은 "전부 보이기"
export const DEFAULT_ITEMS = [
    // {
    //     key: "alba",
    //     label: "단기 알바",
    //     title: "주말·하루 알바\n집안일·심부름·시간제",
    //     image: imageDB.alba,
    //     count: 0,
    //     bgColor: "#FFF3E6",
    // },
    {
        key: "construction",
        label: "건설·토목",
        title: "현장시공·공무·안전관리\n전기·토목·인테리어",
        image: imageDB.construction,
        count: 0,
        bgColor: "#FFEFE0",
    },
    {
        key: "education",
        label: "교육",
        title: "보육·담임·연장·보조\n유치원·어린이·학원",
        image: imageDB.education,
        count: 0,
        bgColor: "#EAF5FF",
    },
    {
        key: "healthcare",
        label: "보건의료",
        title: "병원·요양·의원 운영\n간호·조무·요양·미화",
        image: imageDB.healthcare,
        count: 0,
        bgColor: "#E7FFF6",
    },
    {
        key: "social_worker",
        label: "사회복지사",
        title: "복지관·시설 사무\n행정·상담 보조",
        image: imageDB.social_worker,
        count: 0,
        bgColor: "#FFF1F1",
    },
    {
        key: "caregiver",
        label: "요양보호사",
        title: "방문·시설 요양·돌봄\n간병·목욕·가사지원",
        image: imageDB.caregiver,
        count: 0,
        bgColor: "#FDF2FF",
    },
    {
        key: "it_developer",
        label: "IT·개발",
        title: "웹·앱 개발\n프런트·백엔드",
        image: imageDB.it_developer,
        count: 0,
        bgColor: "#EFF7FF",
    },
    {
        key: "delivery",
        label: "배달",
        title: "운전·주차·화물배송\n택배·물류·창고",
        image: imageDB.delivery,
        count: 0,
        bgColor: "#FFF0E0",
    },
    {
        key: "sales",
        label: "영업·세일즈",
        title: "영업·프로모션\n매장·행사 지원",
        image: imageDB.sales,
        count: 0,
        bgColor: "#FFFBE6",
    },
    {
        key: "disability_friendly",
        label: "장애인 우대",
        title: "배려 채용\n우대 공고",
        image: imageDB.disability_friendly,
        count: 0,
        bgColor: "#EFFAF3",
    },
    {
        key: "food_service",
        label: "요식·외식",
        title: "조리사·주방보조·뷔페\n홀서빙·바리스타",
        image: imageDB.food_service,
        count: 0,
        bgColor: "#FFF7F0",
    },
    {
        key: "tourism",
        label: "관광·서비스",
        title: "관광·레저 안내\n매표·접객",
        image: imageDB.tourism,
        count: 0,
        bgColor: "#EFFFFF",
    },
    {
        key: "agriculture",
        label: "농축산업",
        title: "농장·축사 관리\n수확·사육 보조",
        image: imageDB.agriculture,
        count: 0,
        bgColor: "#F5FFF0",
    },
    {
        key: "cleaning",
        label: "환경·청소",
        title: "건물·시설 미화\n환경 관리",
        image: imageDB.cleaning,
        count: 0,
        bgColor: "#E9F8FF",
    },
    {
        key: "parking",
        label: "검침·주차",
        title: "주차정산·발렛·안내\n검침·점검·원격지원",
        image: imageDB.parking,
        count: 0,
        bgColor: "#FFF7EC",
    },
    {
        key: "ceremony",
        label: "결혼 서비스",
        title: "웨딩·장례 도우미\n의전·안내",
        image: imageDB.ceremony,
        count: 0,
        bgColor: "#FFF0F6",
    },
    {
        key: "security",
        label: "경비원",
        title: "시설·아파트 경비\n순찰·출입 관리",
        image: imageDB.security,
        count: 0,
        bgColor: "#E8F0FF",
    },
    {
        key: "pet_service",
        label: "미용반려",
        title: "반려동물 미용\n돌봄·산책",
        image: imageDB.pet_service,
        count: 0,
        bgColor: "#EFFFF3",
    },
    {
        key: "guard",
        label: "경호·보안",
        title: "단지·매장 보안\n안전요원·보안대원",
        image: imageDB.guard,
        count: 0,
        bgColor: "#F3F3FF",
    },
    {
        key: "childcare",
        label: "돌봄 서비스",
        title: "영유아 담임·연장반\n보육도우미·급식지원",
        image: imageDB.childcare,
        count: 0,
        bgColor: "#FFFCEB",
    },
    {
        key: "restaurant",
        label: "식당 서비스",
        title: "구내식당·산후조리원\n조리사·주방보조·분식",
        image: imageDB.restaurant,
        count: 0,
        bgColor: "#FFF5EC",
    },
    {
        key: "lodging",
        label: "여행숙박",
        title: "호텔·리조트 프론트\n객실·안내",
        image: imageDB.lodging,
        count: 0,
        bgColor: "#EFF9FF",
    },
    {
        key: "chef",
        label: "주방장",
        title: "주방 운영·메뉴 개발\n셰프·수쉐프",
        image: imageDB.chef,
        count: 0,
        bgColor: "#FFF9E6",
    },
    {
        key: "NOSEARCH",
        label: "기타",
        title: "기타·분류 미확인\n전체 공고 모음",
        image: imageDB.construction, // 공용 아이콘
        count: 0,
        bgColor: "#EEF0F5",
    },
];

// ✅ 이제 기본 노출 키도 전부
export const DEFAULT_VISIBLE_KEYS = DEFAULT_ITEMS.map((it) => it.key);
